name: stayhub
description: "Hostel booking & management app."
publish_to: 'none'

version: 1.0.0+115

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- FIREBASE ---
  firebase_core: ^3.15.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.0.0
  cloud_functions: ^5.0.0
  
  # --- CLOUD STORAGE ---
  cloudinary_public: ^0.23.1

  # --- AUTH ---
  google_sign_in: ^6.1.6

  # --- STATE MANAGEMENT ---
  provider: ^6.1.1

  # --- UI & DESIGN ---
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.11

  # --- MEDIA & FILES ---
  image_picker: ^1.0.4
  video_player: ^2.8.1
  cached_network_image: ^3.3.0

  # --- UTILITIES ---
  intl: any
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3 # Added for caching
  timeago: ^3.6.1

  # --- MAPS ---
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  fl_chart: ^1.1.1
  uuid: ^4.5.2
  share_plus: ^10.0.0
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  flutter_cache_manager: ^3.4.1
  location: ^7.0.0
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  http: ^1.6.0
  webview_flutter: ^4.13.0
  flutter_local_notifications: ^19.5.0
  flutter_dotenv: ^5.1.0
  shimmer: ^3.0.0
  email_otp: ^3.1.0
  pinput: ^6.0.1
  app_links: ^6.4.1
  audioplayers: ^6.5.1
  js: ^0.6.3



  path_provider: any
  pointer_interceptor: ^0.10.1+1
  connectivity_plus: ^7.0.0
  google_maps_flutter_android: ^2.19.8
  google_maps_flutter_platform_interface: ^2.15.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/map_style_dark.json
    - assets/map_style_light.json

flutter_native_splash:
  color: "#0F2027"
  image: assets/logo/logo.png
  
  android_12:
    image: assets/logo/logo.png
    color: "#0F2027"
    icon_background_color: "#0F2027"
