// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-4FI84mCzrlhXBU-dxDFrz02TOyGU_Iw',
    appId: '1:33041190550:android:77641061ef371a3d963cb7',
    messagingSenderId: '33041190550',
    projectId: 'device-streaming-d7021871',
    storageBucket: 'device-streaming-d7021871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfNikKB-fgVazhqOlgY8brKqkJUJefCxw',
    appId: '1:33041190550:ios:08b6ae86278b16f4963cb7',
    messagingSenderId: '33041190550',
    projectId: 'device-streaming-d7021871',
    storageBucket: 'device-streaming-d7021871.firebasestorage.app',
    androidClientId: '33041190550-vt1mjs5b97f66auv4u7vgl1pk9ntr21j.apps.googleusercontent.com',
    iosClientId: '33041190550-ko6f8duu712tqbpkmeuv3vo5o6e8ilel.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayhub.stayhub',
  );
}
